name: Slack Bot CI/CD
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Security Scan (SAST)
        run: |
          pip install bandit
          bandit -r . -x tests -ll

      - name: Run Gitleaks
        run: |
          docker run --rm -v $(pwd):/code zricethezav/gitleaks:latest detect --source="/code" -v --no-git

      - name: Build Docker Image
        run: docker build -t slack-bot:latest .

      - name: Deploy to Local Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          
          kubectl rollout restart deployment/slack-bot-deployment